# Generated by Django 3.2.7 on 2021-10-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banios', models.IntegerField(default=0)),
                ('alimentacion', models.BooleanField(default=True)),
                ('valoracion', models.IntegerField(default=0.0)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(default='', max_length=50, verbose_name='Descripcion inmueble')),
                ('ubicacion', models.CharField(default='', max_length=50, verbose_name='Ubicacion inmueble')),
                ('lastChangeDate', models.DateTimeField()),
                ('isAvalaible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('id_inmueble', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='authAppExample.account')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
