# Generated by Django 3.2.7 on 2021-10-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isAvalaible',
            new_name='isAvailable',
        ),
    ]
