# Generated by Django 3.2.7 on 2021-10-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0002_rename_isavalaible_account_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='authAppExample.account'),
        ),
    ]
