# Generated by Django 3.2.7 on 2021-10-12 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0003_alter_user_id_inmueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_inmueble',
        ),
        migrations.AddField(
            model_name='account',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
