# Generated by Django 3.2.8 on 2021-10-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0005_auto_20211007_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destiny_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inmuble_final', to='authAppExample.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inmueble_inicial', to='authAppExample.account'),
        ),
    ]
