# Generated by Django 3.2.8 on 2021-10-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0006_auto_20211007_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destiny_account',
            new_name='inmueble_final',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='origin_account',
            new_name='inmueble_inicial',
        ),
    ]
