# Generated by Django 3.2.7 on 2021-10-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0006_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
