# Generated by Django 3.2.8 on 2021-10-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0007_auto_20211007_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
