# Generated by Django 3.2.7 on 2021-10-15 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0007_remove_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lastChangeDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
