# Generated by Django 3.2.8 on 2021-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0008_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valoracion',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5),
        ),
    ]
