# Generated by Django 3.2.8 on 2021-10-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0009_alter_account_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isAvalaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='valoracion',
            field=models.IntegerField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
